services:
  smart-optimizer-ui:
    image: ghcr.io/mrrobot-88/smart-optimizer-ui:latest
    container_name: smart-optimizer-ui
    network_mode: host
    restart: unless-stopped

    environment:
      # Change this to your local timezone, for example:
      # Europe/London, Europe/Stockholm, America/New_York
      TZ: Etc/UTC
      SMART_UI_HOST: 0.0.0.0
      SMART_UI_PORT: 8788

    volumes:
      - ./config:/config
      - ./data:/data
