#!/bin/sh
set -eu
mkdir -p "$SYNOPKG_PKGVAR/config" "$SYNOPKG_PKGVAR/data" "$SYNOPKG_PKGVAR/tmp" "$SYNOPKG_PKGVAR/updates" "$SYNOPKG_PKGVAR/app/releases"
chmod 700 "$SYNOPKG_PKGVAR/config" "$SYNOPKG_PKGVAR/data"
exit 0
